# Router Configuration.

[module]
role = "router"
clusterId = "1"
ip = "0.0.0.0"
httpPort = 9000
pprof = 10088
masterAddr = "localhost:18817"
masterConnPoolSize = 10
psConnPoolSize = 10

[log]
log-path = "/tmp/router_log"
#debug, info, warn, error
level="debug"
